name: Check main for vulns daily

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read
  issues: write

jobs:
  check-vulns:
    uses: ./.github/workflows/check-vulns.yml
    with:
      nodejsStream: main
    secrets: inherit
